title: Shoku Ai
description: Witaj! ShokuAi to mobilna aplikacja do generowania przepisów i tworzenia listy zakupów.
show_downloads: true

baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://paulinalewicka1.github.io/ShokuAi/" # change this to the base hostname & protocol for your site


# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

#theme: # leave it empty
#theme: jekyll-theme-cayman-blog
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-target-blank
  - kramdown-parser-gfm

target-blank:
    rel: nofollow

header_page_refs: ['tutorial', 'contact']

markdown: kramdown
