remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Shoku Ai]
description: [Witaj! ShokuAi to mobilna aplikacja do generowania przepisów i tworzenia listy zakupów.]